#+OPTIONS: toc:nil ^:nil author:nil date:nil html-postamble:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+TITLE: meeting notes

** Shift Sports answer connection to structured index OS tables
SCHEDULED: <2017-02-16 Thu>
**** Finish migration of NHL as the first try in the coming week [Feb.20-24]
@Bichong Li first verify the data existence
@John Guo finish the final verify and migrate

**** Delay the cut-off of sport private pipeline for 2 more months
@Bert Wu@Bichong Li will talk with Guangping and Kit for an overall plan

**** Esports’s solution
@Changyan Liu helps to confirm whether the data goes through John’s pipeline or not & confirm xap plug-in is needed for overlay play

**** A domain list of who is using John’s pipeline
@John Guo

** "id:" -> caption query in ImageUX scenarios
SCHEDULED: <2017-02-15 Wed>
*** UX doesn’t change request structure at all.  Instead, backend will help transform MID into caption requests to help optimize IS serving load.
*** Video team already working on the pipeline to support caption requests.  Setup time until now has taken about 1 month.
*** Building a mapping table for Mainline (MID -> NoduleHash) & Fresh (MID -> ICUID).
*** XAP plugin that will help pass UX requests to caption queries and transform the response to suitable schema.
*** Major open issues
**** Adult & region blocking – today’s pipeline relies on caption metadata to help decide whether doc is adult or to block for certain region.  Need to replicate this functionality in new design.
**** Image IG team will review Video’s architecture & design to see how / when image team will migrate.
**** Biggest concern is scalability.
*** Timeline TBD.
@Alex / @Bichong, can you share the timeline when you guys have better idea?  I’d like to keep track of the progress and see how we can help reduce load as we grow the index 2x & 10x.
