#+OPTIONS: toc:nil ^:nil author:nil date:nil html-postamble:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+TITLE: 工作效率

** 提升工作效率的45个小技巧
1. 最重要的事
   在每天早上（或前一天晚上），重点列出今天要做3件或者4件最重要的事情，先完成这些。即使你除开这些重要事项就没有完成其他的事，但还是度过了非常有成效的一天。
2. 大家伙
   就是你一直都在做的项目。每天或每周专门给它留出时间来做，一步步完成。
3. 清空收件箱
   一收到邮件就觉得如何处理。如果是需要你做一些动作，要么做，要么加入待办事项，要么删除，要么存档；如果只是供你参考的邮件，就把它存档吧。清空你的收件箱。
4. 早起半小时
   在别人支配你的时间之前，早起半小时就等于一天多了极副成效的半个小时。
5. 头脑风暴
   以你正在想的事情为起始点，然后随手写下你头脑中的任何想法，再扩展到每个想法的副主题以及副主题的副主题。不用担心这些想法是好是坏，也不需要在这个想法下一直坚持下去。过一阵子之后，你自己都会惊讶于你有多少创意电子。
6. 随时记录
   随身携带可记录的东西，捕捉你头脑中闪过的每一个想法，无论是关于你可能从事的项目，或是你需要敲定的一个约会。经常拿出来看看，逐个归类到待办事项，存档。
7. (10 + 2) * 5
   10 分钟迅速工作，中间休息两分钟，用上计数器，每个小时这样做五次，让你始终集中在工作上而不会让你精疲力尽。把休息的两分钟用来喝口水，去去洗手间或是看会儿窗外。
8. SMART目标：
   明确的，可测量的，可达到的，现实的，实时的。借助这个原则来描述制定、达到你的目标，并避免设定一些不实在的目标。
9. 先吞下青蛙：
   最先做你最不愿意的事情。如果你的一天是以吃青蛙来开始的，那么你这一天不可能更糟糕了。
10. 80/20准则
    大部分的成就来源于小部分的实际工作，反过来说就是，我们大部分的精力花费在那些不是很重要的事情上。找出你工作最关键的部分，尽可能地把你的精力放在那上面。
11. 下一步是什么？
    不要试图计划项目中的每一件事，集中精力在紧挨着的下一步，通常下一步的小事情就会将我们引导到另一步，直到我们把他完成或是遇到阻碍停下来，这时你就知道是否需要更多的信息，或需要其他人的加入。
12. 放慢点
    给自己留出时间，吃慢点。享受一个懒洋洋的周末，悠闲地做事，保持快节奏的工作与生活的平衡。
13. 时间搏击
    每天安排一段时间来处理一个工作。在这段时间中集中注意力完全集中在这件事上面，不要一直担心是否能够完成，只需给与这项工作全部的关注。
14. 分批处理
    把类似的工作放到一起来做。例如：不要整天都在处理那些不时出现的邮件，而是用专门一小时来浏览你的收件箱以及回邮件。同样的方法处理留言，电话，回信，存档等等一切日常、重复的工作。
15. 划分象限
    画两个轴，一个代表重要性，一个代表紧急程度，二者相交。所有的任务都归类到四个象限中的其中一个：不重要不紧急；不重要但紧急；重要不紧急；重要且紧急。去掉那些既不重要也不紧急的事情，推迟那些不重要但紧急的事情，尽量避免让那些重要事情变得紧急，尽可能快的完成那些重要但是不紧急的事项。
16. 一次性解决
    不要寄希望于把事情留到以后来处理。每次处理你的邮件时，问自己“我怎么处理这个东西”，要么做，要么放到日程上，要么转给别人做，要么存档。
17. 不要打断链条
    用一个日历纪录你每天的目标。把你每天完成的事项划上一个大大的叉号，这个链条会一天天变长，不要让他断掉，
18. 回顾
    安排时间来检视这个星期做了些什么，下个星期希望做些什么。问自己，是否有新的计划，现在做的是否让你更接近你的人生目标。经常反省。
19. 角色平衡
    理解生活中每个不同的角色，学着把他们各自区分开来有助于你保持各个角色的平衡。
20. 泉涌状态
    极其专心在某件事情上的时候，甚至没有感觉到时间的流逝。而同时工作就顺利完成。这种状态很难通过有意识的引发，但是你可以自己创造引发这种状态的条件，不如一段不受打扰的时间，不分心，心境平和。
21. 现在就做
    只给自己60秒的时间来做决定，当下决定如何解决生活中遇到的事情，即使你还不是很确定也要尝试着做决定，然后，一直前进。
22. 时间记录
    记录每项事情上花费的时间
23. 向后计划
    首先在心中确立要达成的目标，需要哪些可用资源去达成，然后又需要哪些资源去达成目标的条件，而这些东西又需要什么东西去达到等等，一直反推到我们拥有的可以马上使用的东西，这就确定了下一步。
24. 戴上耳机
    给自己一点私人的空间和时间，不被人打扰。
25. 写下来
    不要太依赖于你的记忆力，把你要做的事情写下来，任何你涉及到事情，一闪而过的点子，记录下来就不用担心会忘掉。
26. 零碎时间
    等公交车，排队，等待开会的那一段时间，列出可以五分钟完成的任务。
27. 单个任务
    总把自己想成可以同时处理多项任务，事实上我们不能。当处理多任务的时候，实际上是把时间切碎并在多个任务上快速的切换。因为通常需要花上一段时间才能真正进入状态（研究证明长达20分钟），事情还是一件件来。
28. 清理
    经常检查你正在做的事情，把那些不能帮助你达成目标或是总浪费你时间、精力的去掉。
29. 采集
    把你收集到的东西和想法集中起来
30. 跟自己对话
    每个星期给自己安排一段时间，想象你自己的工作状态：什么上轨道了，什么还没有，我犯了什么错了吗？我可以做哪些改变，让自己更了解自己。
